---
- name: Add Oracle Public Repos
  get_url:
    url: "http://public-yum.oracle.com/public-yum-ol{{ ansible_distribution_major_version }}.repo"
    dest: '/etc/yum.repos.d'
  become: true

- name: Add Oracle Public Repo GPG Key
  get_url:
    url: "http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol{{ ansible_distribution_major_version }}"
    dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-oracle'
  become: true
